### ISSUE TITLE
how can i open the source code? IM NEW.

### ISSUE THREAD

**Issue by Wouze** [yasirrhaq/EPIC-RPG-Autotyper#3]
can somone tell me how to open the source code? i tryed opening the source code with note pad but it didnt work.

**Comment by AlexisTM** [comment]
The code is not shared, do not use this, there could easily be malwares included.

**Comment by Wouze** [comment]
What do you mean??

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by AlexisTM** [comment]
There is no source code provided. That means anything can be added to the executable provided. A malware with full access to the machine is about 5 lines of code, so you should always be wary of software from unknown sources.
Note that even when the source is provided, nothing prevents shady developers to add malwares to the prebuilt executable.  

Otherwise, the source code should be on the main page of the project next to the "README.md".

**Comment by yasirrhaq** [comment]
Hi there, sorry for the late reply. I don't really think I still have the code for it (idk where the source code is, since I've changed my laptop) and i don't think i will continue this project anymore in the near time but if I have spare time ill make a new one and make it open source and you guys can contribute. Thanks
